
BEGIN;

    CREATE TABLE tbl_users(
        id SERIAL PRIMARY KEY,
        is_verified BOOLEAN NOT NULL DEFAULT FALSE,
        name VARCHAR(255) NOT NULL,
        gender VARCHAR(6) NOT NULL,
        email VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        age INTEGER NOT NULL,
        bio text NOT NULL,
        photo_url VARCHAR(255) NOT NULL,
        created_at timestamp NOT NULL DEFAULT (now()),
        updated_at timestamp DEFAULT (now()),
        UNIQUE(email)
    );


    INSERT INTO tbl_users (is_verified, name, gender, email, password, age, bio, photo_url, created_at, updated_at)
    VALUES
        (TRUE, 'Rizki Aditya', 'male', 'rizki.aditya@example.com', 'hashedpassword1', 25, 'Pencinta kopi, perjalanan, dan selalu mencoba diet yang gagal.', 'https://example.com/photos/rizki_aditya.jpg', NOW(), NOW()),
        (FALSE, 'Bima Pradipta', 'male', 'bima.pradipta@example.com', 'hashedpassword2', 30, 'Cuma bisa nonton film, tapi nggak pernah tahu akhir cerita.', 'https://example.com/photos/bima_pradipta.jpg', NOW(), NOW()),
        (TRUE, 'Arga Wicaksono', 'male', 'arga.wicaksono@example.com', 'hashedpassword3', 28, 'Selalu berusaha lari pagi tapi selalu ketiduran.', 'https://example.com/photos/arga_wicaksono.jpg', NOW(), NOW()),
        (TRUE, 'Putri Maharani', 'female', 'putri.maharani@example.com', 'hashedpassword4', 26, 'Penyuka drama Korea dan ngidam makanan 24/7.', 'https://example.com/photos/putri_maharani.jpg', NOW(), NOW()),
        (FALSE, 'Dimas Setyo', 'male', 'dimas.setyo@example.com', 'hashedpassword5', 31, 'Ngaku pencinta seni, tapi nggak ngerti apa itu seni.', 'https://example.com/photos/dimas_setyo.jpg', NOW(), NOW()),
        (TRUE, 'Alam Nugraha', 'male', 'alam.nugraha@example.com', 'hashedpassword6', 34, 'Hobi ke pantai, tapi nggak bisa renang.', 'https://example.com/photos/alam_nugraha.jpg', NOW(), NOW()),
        (FALSE, 'Nadya Rahma', 'female', 'nadya.rahma@example.com', 'hashedpassword7', 29, 'Suka ngopi tapi nggak pernah ngerti cara bikin kopi yang benar.', 'https://example.com/photos/nadya_rahma.jpg', NOW(), NOW()),
        (TRUE, 'Tari Anjani', 'female', 'tari.anjani@example.com', 'hashedpassword8', 24, 'Ngaku penyuka buku, tapi lebih sering main Instagram.', 'https://example.com/photos/tari_anjani.jpg', NOW(), NOW()),
        (FALSE, 'Arief Saputra', 'male', 'arief.saputra@example.com', 'hashedpassword9', 35, 'Suka meditasi, tapi belum pernah coba yoga.', 'https://example.com/photos/arief_saputra.jpg', NOW(), NOW()),
        (TRUE, 'Ayu Indira', 'female', 'ayu.indira@example.com', 'hashedpassword10', 33, 'Bergaya bohemian, tapi tetap bawa tas modern.', 'https://example.com/photos/ayu_indira.jpg', NOW(), NOW()),
        (TRUE, 'Bayu Perdana', 'male', 'bayu.perdana@example.com', 'hashedpassword11', 27, 'Hobi mendaki gunung, tapi lebih banyak foto selfie di puncak.', 'https://example.com/photos/bayu_perdana.jpg', NOW(), NOW()),
        (FALSE, 'Reza Fauzan', 'male', 'reza.fauzan@example.com', 'hashedpassword12', 32, 'Orang yang bilang "santai saja" tapi tetap terburu-buru.', 'https://example.com/photos/reza_fauzan.jpg', NOW(), NOW()),
        (TRUE, 'Gilang Pratama', 'male', 'gilang.pratama@example.com', 'hashedpassword13', 29, 'Penyuka sejarah, tapi nggak tahu siapa yang menang Piala Dunia terakhir.', 'https://example.com/photos/gilang_pratama.jpg', NOW(), NOW()),
        (FALSE, 'Salsabila Putri', 'female', 'salsabila.putri@example.com', 'hashedpassword14', 28, 'Suka nonton drama, tapi akhirnya tidur sebelum episode terakhir.', 'https://example.com/photos/salsabila_putri.jpg', NOW(), NOW()),
        (TRUE, 'Dandi Kurnia', 'male', 'dandi.kurnia@example.com', 'hashedpassword15', 36, 'Suka bersepeda, tapi nggak pernah mau bawa sepeda sendiri.', 'https://example.com/photos/dandi_kurnia.jpg', NOW(), NOW()),
        (FALSE, 'Rara Melati', 'female', 'rara.melati@example.com', 'hashedpassword16', 34, 'Dibilang romantis, tapi lebih suka tidur tanpa gangguan.', 'https://example.com/photos/rara_melati.jpg', NOW(), NOW()),
        (TRUE, 'Sri Lestari', 'female', 'sri.lestari@example.com', 'hashedpassword17', 27, 'Penyuka binatang, tapi alergi sama kucing.', 'https://example.com/photos/sri_lestari.jpg', NOW(), NOW()),
        (FALSE, 'Aldi Ramadhan', 'male', 'aldi.ramadhan@example.com', 'hashedpassword18', 40, 'Pemimpin yang inspiratif, tapi nggak bisa masak mie instan.', 'https://example.com/photos/aldi_ramadhan.jpg', NOW(), NOW()),
        (TRUE, 'Raka Wijaya', 'male', 'raka.wijaya@example.com', 'hashedpassword19', 45, 'Pendengar yang baik, tapi sering ketiduran di tengah cerita.', 'https://example.com/photos/raka_wijaya.jpg', NOW(), NOW()),
        (TRUE, 'Fajar Iskandar', 'male', 'fajar.iskandar@example.com', 'hashedpassword20', 26, 'Suka mencoba hal baru, termasuk diet keto yang nggak pernah berhasil.', 'https://example.com/photos/fajar_iskandar.jpg', NOW(), NOW()),
        (FALSE, 'Cinta Larasati', 'female', 'cinta.larasati@example.com', 'hashedpassword21', 39, 'Penyuka film horor, tapi takut nonton sendirian.', 'https://example.com/photos/cinta_larasati.jpg', NOW(), NOW()),
        (TRUE, 'Bintang Saputra', 'male', 'bintang.saputra@example.com', 'hashedpassword22', 31, 'Selalu semangat kerja, tapi tiba-tiba ngantuk saat rapat.', 'https://example.com/photos/bintang_saputra.jpg', NOW(), NOW()),
        (FALSE, 'Maya Astari', 'female', 'maya.astari@example.com', 'hashedpassword23', 25, 'Suka fashion, tapi kadang bingung mau pakai apa untuk acara santai.', 'https://example.com/photos/maya_astari.jpg', NOW(), NOW()),
        (TRUE, 'Anisa Fadhila', 'female', 'anisa.fadhila@example.com', 'hashedpassword24', 29, 'Penyuka anak-anak, tapi kadang lebih suka tidur siang.', 'https://example.com/photos/anisa_fadhila.jpg', NOW(), NOW()),
        (FALSE, 'Iqbal Maulana', 'male', 'iqbal.maulana@example.com', 'hashedpassword25', 38, 'Pengusaha yang ambisius, tapi susah tidur karena begadang main game.', 'https://example.com/photos/iqbal_maulana.jpg', NOW(), NOW()),
        (TRUE, 'Daffa Putra', 'male', 'daffa.putra@example.com', 'hashedpassword26', 28, 'Suka fotografi, tapi lebih sering foto makanan di Instagram.', 'https://example.com/photos/daffa_putra.jpg', NOW(), NOW()),
        (TRUE, 'Farah Safira', 'female', 'farah.safira@example.com', 'hashedpassword27', 24, 'Blogger yang selalu nulis, kecuali waktu diet mulai gagal.', 'https://example.com/photos/farah_safira.jpg', NOW(), NOW()),
        (FALSE, 'Indra Kurniawan', 'male', 'indra.kurniawan@example.com', 'hashedpassword28', 33, 'Suka berpetualang dan menemukan jalan-jalan tersembunyi, tapi lebih sering nyasar.', 'https://example.com/photos/indra_kurniawan.jpg', NOW(), NOW()),
        (TRUE, 'Dina Amalia', 'female', 'dina.amalia@example.com', 'hashedpassword29', 26, 'Penyuka desain, tapi nggak tahu cara memakai wallpaper di smartphone.', 'https://example.com/photos/dina_amalia.jpg', NOW(), NOW()),
        (FALSE, 'Bagus Santoso', 'male', 'bagus.santoso@example.com', 'hashedpassword30', 29, 'Selalu berusaha jadi baik, tapi kadang lupa nama orang.', 'https://example.com/photos/bagus_santoso.jpg', NOW(), NOW()),
        (TRUE, 'Nadira Alifia', 'female', 'nadira.alifia@example.com', 'hashedpassword31', 27, 'Penyuka lingkungan, tapi kadang lupa bawa tas belanjaan sendiri.', 'https://example.com/photos/nadira_alifia.jpg', NOW(), NOW()),
        (FALSE, 'Eka Yudha', 'male', 'eka.yudha@example.com', 'hashedpassword32', 34, 'Suka bersepeda, tapi lebih sering di jalan tanpa arah tujuan.', 'https://example.com/photos/eka_yudha.jpg', NOW(), NOW()),
        (TRUE, 'Lia Kartika', 'female', 'lia.kartika@example.com', 'hashedpassword33', 30, 'Penyuka petualangan, tapi takut kena macet di Jakarta.', 'https://example.com/photos/lia_kartika.jpg', NOW(), NOW()),
        (FALSE, 'Rudi Kurniawan', 'male', 'rudi.kurniawan@example.com', 'hashedpassword34', 31, 'Gila tantangan, tapi kadang kebanyakan tidur.', 'https://example.com/photos/rudi_kurniawan.jpg', NOW(), NOW()),
        (TRUE, 'Siti Farida', 'female', 'siti.farida@example.com', 'hashedpassword35', 29, 'Menikmati waktu tenang, tapi sering lupa matikan lampu kamar.', 'https://example.com/photos/siti_farida.jpg', NOW(), NOW()),
        (FALSE, 'Fauzan Dwi', 'male', 'fauzan.dwi@example.com', 'hashedpassword36', 33, 'Penyuka masakan Indonesia, tapi lebih sering beli makanan instan.', 'https://example.com/photos/fauzan_dwi.jpg', NOW(), NOW()),
        (TRUE, 'Sabrina Putri', 'female', 'sabrina.putri@example.com', 'hashedpassword37', 26, 'Suka nonton film action, tapi malah tidur saat adegan keren.', 'https://example.com/photos/sabrina_putri.jpg', NOW(), NOW()),
        (FALSE, 'Johan Harjanto', 'male', 'johan.harjanto@example.com', 'hashedpassword38', 34, 'Hobi berolahraga, tapi nggak pernah sempat ke gym.', 'https://example.com/photos/johan_harjanto.jpg', NOW(), NOW()),
        (TRUE, 'Gita Rizka', 'female', 'gita.rizka@example.com', 'hashedpassword39', 28, 'Penyuka musik, tapi kadang salah nyanyi lirik lagu.', 'https://example.com/photos/gita_rizka.jpg', NOW(), NOW()),
        (FALSE, 'Ivan Pratama', 'male', 'ivan.pratama@example.com', 'hashedpassword40', 32, 'Penyuka teknologi, tapi bingung cara setting TV baru.', 'https://example.com/photos/ivan_pratama.jpg', NOW(), NOW()),
        (TRUE, 'Yusuf Ardi', 'male', 'yusuf.ardi@example.com', 'hashedpassword1', 27, 'Selalu punya ide besar, tapi sering lupa di mana menaruh kunci mobil.', 'https://example.com/photos/yusuf_ardi.jpg', NOW(), NOW()),
        (FALSE, 'Mira Hesti', 'female', 'mira.hesti@example.com', 'hashedpassword2', 32, 'Tunggu, apakah ini swipe kanan atau kiri? Ah, biarkan saja.', 'https://example.com/photos/mira_hesti.jpg', NOW(), NOW()),
        (TRUE, 'Arjuna Prawira', 'male', 'arjuna.prawira@example.com', 'hashedpassword3', 29, 'Hobi main game dan cuma bisa makan ramen instan.', 'https://example.com/photos/arjuna_prawira.jpg', NOW(), NOW()),
        (TRUE, 'Nina Adelia', 'female', 'nina.adelia@example.com', 'hashedpassword4', 24, 'Hanya bisa selfie di tempat yang terang, kalau nggak, wajahnya gelap.', 'https://example.com/photos/nina_adelia.jpg', NOW(), NOW()),
        (FALSE, 'Iqbal Reza', 'male', 'iqbal.reza@example.com', 'hashedpassword5', 31, 'Sering menghabiskan waktu di tempat kopi, tapi nggak pernah tahu apa yang dimaksud dengan "latte art".', 'https://example.com/photos/iqbal_reza.jpg', NOW(), NOW()),
        (TRUE, 'Rina Sukmawati', 'female', 'rina.sukmawati@example.com', 'hashedpassword6', 26, 'Suka nyanyi di kamar mandi, meskipun nggak pernah bisa nyanyi dengan benar.', 'https://example.com/photos/rina_sukmawati.jpg', NOW(), NOW()),
        (FALSE, 'Fadli Fikri', 'male', 'fadli.fikri@example.com', 'hashedpassword7', 28, 'Lebih suka ngoding daripada ngobrol, tapi kadang perlu juga ngobrol sama teman-teman.', 'https://example.com/photos/fadli_fikri.jpg', NOW(), NOW()),
        (TRUE, 'Klara Novita', 'female', 'klara.novita@example.com', 'hashedpassword8', 33, 'Menyukai seni lukis, tapi gambar stickman pun udah merasa bangga.', 'https://example.com/photos/klara_novita.jpg', NOW(), NOW()),
        (FALSE, 'Denny Satria', 'male', 'denny.satria@example.com', 'hashedpassword9', 35, 'Suka pergi ke gym, tapi baru tahu bahwa gym adalah singkatan dari “gabut yuk malah makan”.', 'https://example.com/photos/denny_satria.jpg', NOW(), NOW()),
        (TRUE, 'Sarah Indah', 'female', 'sarah.indah@example.com', 'hashedpassword10', 27, 'Hobi dandan tapi tetap nggak paham cara pakai eyeliner dengan benar.', 'https://example.com/photos/sarah_indah.jpg', NOW(), NOW()),
        (FALSE, 'Alif Hasan', 'male', 'alif.hasan@example.com', 'hashedpassword11', 34, 'Pencinta kopi, tapi nggak pernah bisa membedakan jenis kopi yang sebenarnya.', 'https://example.com/photos/alif_hasan.jpg', NOW(), NOW()),
        (TRUE, 'Lita Juwita', 'female', 'lita.juwita@example.com', 'hashedpassword12', 29, 'Hobi berbicara tanpa henti, tapi nggak pernah dengerin diri sendiri.', 'https://example.com/photos/lita_juwita.jpg', NOW(), NOW()),
        (FALSE, 'Gilang Priyanto', 'male', 'gilang.pryanto@example.com', 'hashedpassword13', 27, 'Ngaku pemain musik, tapi lebih banyak main TikTok daripada gitar.', 'https://example.com/photos/gilang_priyanto.jpg', NOW(), NOW()),
        (TRUE, 'Dina Anjani', 'female', 'dina.anjani@example.com', 'hashedpassword14', 30, 'Selalu punya cara untuk menghindari tugas rumah, tapi tetap menyelesaikannya dalam waktu 10 menit.', 'https://example.com/photos/dina_anjani.jpg', NOW(), NOW()),
        (FALSE, 'Rayhan Adi', 'male', 'rayhan.adi@example.com', 'hashedpassword15', 26, 'Suka travelling, tapi sering kebablasan sampai ke tempat yang nggak pernah didengar sebelumnya.', 'https://example.com/photos/rayhan_adi.jpg', NOW(), NOW()),
        (TRUE, 'Anggi Setiawan', 'male', 'anggi.setiawan@example.com', 'hashedpassword16', 32, 'Sering jadi pengemudi Gojek, kadang malah jadi penumpang buat diri sendiri.', 'https://example.com/photos/anggi_setiawan.jpg', NOW(), NOW()),
        (FALSE, 'Jessica Aulia', 'female', 'jessica.aulia@example.com', 'hashedpassword17', 29, 'Bergaya ala fashionista, tapi sering bingung mau pakai baju apa.', 'https://example.com/photos/jessica_aulia.jpg', NOW(), NOW()),
        (TRUE, 'Vera Ayu', 'female', 'vera.ayu@example.com', 'hashedpassword18', 28, 'Tahu banyak tentang fashion, tapi selalu ketinggalan tren terbaru.', 'https://example.com/photos/vera_ayu.jpg', NOW(), NOW()),
        (FALSE, 'Darren Wicaksono', 'male', 'darren.wicaksono@example.com', 'hashedpassword19', 33, 'Sering punya ide cemerlang, tapi nggak pernah menerapkannya karena ketiduran.', 'https://example.com/photos/darren_wicaksono.jpg', NOW(), NOW()),
        (TRUE, 'Asha Rosita', 'female', 'asha.rosita@example.com', 'hashedpassword20', 34, 'Penyuka pizza, tapi nggak suka kalau topping-nya lebih banyak dari keju.', 'https://example.com/photos/asha_rosita.jpg', NOW(), NOW()),
        (FALSE, 'Hendra Prasetya', 'male', 'hendra.prasetya@example.com', 'hashedpassword21', 38, 'Suka coding, tapi nggak pernah berhasil bikin aplikasi yang stabil.', 'https://example.com/photos/hendra_prasetya.jpg', NOW(), NOW()),
        (TRUE, 'Tika Khairunnisa', 'female', 'tika.khairunnisa@example.com', 'hashedpassword22', 27, 'Lebih suka makan nasi goreng sambil nonton drakor, tapi belum pernah ke Korea.', 'https://example.com/photos/tika_khairunnisa.jpg', NOW(), NOW()),
        (FALSE, 'Yogi Saputra', 'male', 'yogi.saputra@example.com', 'hashedpassword23', 25, 'Selalu coba diet sehat, tapi akhirnya kembali ke mie instan tiap malam.', 'https://example.com/photos/yogi_saputra.jpg', NOW(), NOW()),
        (TRUE, 'Nadia Fitri', 'female', 'nadia.fitri@example.com', 'hashedpassword24', 28, 'Selalu kelupaan password akun media sosial, jadi sering reset password deh.', 'https://example.com/photos/nadia_fitri.jpg', NOW(), NOW()),
        (FALSE, 'Irfan Muhammad', 'male', 'irfan.muhammad@example.com', 'hashedpassword25', 36, 'Suka mendaki gunung, tapi kebanyakan bawa barang yang nggak perlu.', 'https://example.com/photos/irfan_muhammad.jpg', NOW(), NOW()),
        (TRUE, 'Dewi Kartika', 'female', 'dewi.kartika@example.com', 'hashedpassword26', 30, 'Mencoba hidup sehat, tapi tiap hari selalu lewat di depan kafe kopi.', 'https://example.com/photos/dewi_kartika.jpg', NOW(), NOW()),
        (FALSE, 'Anton Wibowo', 'male', 'anton.wibowo@example.com', 'hashedpassword27', 32, 'Senang ngumpul sama teman, tapi nggak pernah bawa oleh-oleh apapun.', 'https://example.com/photos/anton_wibowo.jpg', NOW(), NOW()),
        (TRUE, 'Rini Suryani', 'female', 'rini.suryani@example.com', 'hashedpassword28', 25, 'Suka dandan, tapi tetap nggak bisa bedain warna lipstik.', 'https://example.com/photos/rini_suryani.jpg', NOW(), NOW()),
        (FALSE, 'Bagus Darmawan', 'male', 'bagus.darmawan@example.com', 'hashedpassword29', 33, 'Suka main bola, tapi lebih banyak jadi penjaga gawang di video game.', 'https://example.com/photos/bagus_darmawan.jpg', NOW(), NOW()),
        (TRUE, 'Rika Yuliana', 'female', 'rika.yuliana@example.com', 'hashedpassword30', 28, 'Suka olahraga, tapi lebih sering bingung di gym tentang mesin yang mana harus digunakan.', 'https://example.com/photos/rika_yuliana.jpg', NOW(), NOW()),
        (FALSE, 'Hadi Arifin', 'male', 'hadi.arifin@example.com', 'hashedpassword31', 29, 'Bisa masak, tapi cuma tahu cara bikin mie instan dan telur dadar.', 'https://example.com/photos/hadi_arifin.jpg', NOW(), NOW()),
        (TRUE, 'Tika Mawarni', 'female', 'tika.mawarni@example.com', 'hashedpassword32', 26, 'Hobi berenang, tapi cuma bisa gaya katak dengan kecepatan 0.1 meter per detik.', 'https://example.com/photos/tika_mawarni.jpg', NOW(), NOW()),
        (FALSE, 'Randy Putra', 'male', 'randy.putra@example.com', 'hashedpassword33', 31, 'Penyuka mobil, tapi sering bingung dengan fitur mobil modern.', 'https://example.com/photos/randy_putra.jpg', NOW(), NOW()),
        (TRUE, 'Dinda Nurul', 'female', 'dinda.nurul@example.com', 'hashedpassword34', 28, 'Suka berkebun, tapi lebih banyak tanaman mati daripada hidupnya.', 'https://example.com/photos/dinda_nurul.jpg', NOW(), NOW()),
        (FALSE, 'Mukti Wijaya', 'male', 'mukti.wijaya@example.com', 'hashedpassword35', 34, 'Pencinta teknologi, tapi nggak pernah berhasil update aplikasi di ponsel dengan benar.', 'https://example.com/photos/mukti_wijaya.jpg', NOW(), NOW()),
        (TRUE, 'Cindy Sari', 'female', 'cindy.sari@example.com', 'hashedpassword36', 29, 'Selalu bilang lagi diet, tapi akhirnya makan donat.', 'https://example.com/photos/cindy_sari.jpg', NOW(), NOW()),
        (TRUE, 'Rizki Fauzan', 'male', 'rizki.fauzan@example.com', 'hashedpassword1', 28, 'Punya banyak koleksi sepatu, tapi sering bingung mau pakai yang mana.', 'https://example.com/photos/rizki_fauzan.jpg', NOW(), NOW()),
        (FALSE, 'Alisha Rahmawati', 'female', 'alisha.rahmawati@example.com', 'hashedpassword2', 25, 'Coba-coba diet, tapi selalu gagal setiap ada pizza.', 'https://example.com/photos/alisha_rahmawati.jpg', NOW(), NOW()),
        (TRUE, 'Arief Dwi', 'male', 'arief.dwi@example.com', 'hashedpassword3', 29, 'Suka nonton film horor, tapi takut sendiri pas malam minggu.', 'https://example.com/photos/arief_dwi.jpg', NOW(), NOW()),
        (TRUE, 'Jessica Maharani', 'female', 'jessica.maharani@example.com', 'hashedpassword4', 27, 'Hobi traveling, tapi lebih banyak foto di hotel daripada di tempat wisata.', 'https://example.com/photos/jessica_maharani.jpg', NOW(), NOW()),
        (FALSE, 'Dion Wira', 'male', 'dion.wira@example.com', 'hashedpassword5', 31, 'Sering masak mie instan, tapi bilangnya sudah jadi chef handal.', 'https://example.com/photos/dion_wira.jpg', NOW(), NOW()),
        (TRUE, 'Putri Dewi', 'female', 'putri.dewi@example.com', 'hashedpassword6', 24, 'Suka ngemil coklat sambil nonton drama Korea, bisa sampai lupa waktu.', 'https://example.com/photos/putri_dewi.jpg', NOW(), NOW()),
        (FALSE, 'Andi Kurniawan', 'male', 'andi.kurniawan@example.com', 'hashedpassword7', 28, 'Pencinta sepak bola, tapi lebih sering ngumpul sama teman-teman untuk nonton Netflix.', 'https://example.com/photos/andi_kurniawan.jpg', NOW(), NOW()),
        (TRUE, 'Sari Rachmawati', 'female', 'sari.rachmawati@example.com', 'hashedpassword8', 26, 'Bisa berjam-jam ngomongin fashion, tapi masih bingung bedain warna celana jeans.', 'https://example.com/photos/sari_rachmawati.jpg', NOW(), NOW()),
        (FALSE, 'Faisal Bagus', 'male', 'faisal.bagus@example.com', 'hashedpassword9', 30, 'Ngaku bisa main gitar, tapi belum pernah bikin lagu yang keren.', 'https://example.com/photos/faisal_bagus.jpg', NOW(), NOW()),
        (TRUE, 'Dina Prameswari', 'female', 'dina.prameswari@example.com', 'hashedpassword10', 29, 'Selalu punya ide untuk pesta ulang tahun, tapi akhirnya hanya duduk di rumah saja.', 'https://example.com/photos/dina_prameswari.jpg', NOW(), NOW()),
        (FALSE, 'Randi Setiawan', 'male', 'randi.setiawan@example.com', 'hashedpassword11', 32, 'Punya banyak akun media sosial, tapi sering bingung kenapa followers malah makin sedikit.', 'https://example.com/photos/randi_setiawan.jpg', NOW(), NOW()),
        (TRUE, 'Alya Nadya', 'female', 'alya.nadya@example.com', 'hashedpassword12', 25, 'Selalu bilang “saya lagi diet”, tapi akhirnya makan nasi padang dua kali seminggu.', 'https://example.com/photos/alya_nadya.jpg', NOW(), NOW()),
        (FALSE, 'Kevin Aditya', 'male', 'kevin.aditya@example.com', 'hashedpassword13', 28, 'Sering selfie, tapi bingung kenapa nggak pernah bisa dapat angle yang bagus.', 'https://example.com/photos/kevin_aditya.jpg', NOW(), NOW()),
        (TRUE, 'Rani Rahayu', 'female', 'rani.rahayu@example.com', 'hashedpassword14', 31, 'Hobi belanja, tapi akhirnya baju yang dibeli cuma jadi pajangan di lemari.', 'https://example.com/photos/rani_rahayu.jpg', NOW(), NOW()),
        (FALSE, 'Ivan Firdaus', 'male', 'ivan.firdaus@example.com', 'hashedpassword15', 33, 'Pencinta kopi, tapi sering lupa kalau kafein bikin susah tidur.', 'https://example.com/photos/ivan_firdaus.jpg', NOW(), NOW()),
        (TRUE, 'Fiona Zahra', 'female', 'fiona.zahra@example.com', 'hashedpassword16', 27, 'Suka memotret pemandangan, tapi lebih banyak foto makanan di galeri handphone.', 'https://example.com/photos/fiona_zahra.jpg', NOW(), NOW()),
        (FALSE, 'Fadhil Haris', 'male', 'fadhil.haris@example.com', 'hashedpassword17', 29, 'Hobi main game, tapi lebih sering nonton orang main game di YouTube.', 'https://example.com/photos/fadhil_haris.jpg', NOW(), NOW()),
        (TRUE, 'Rizki Elvira', 'female', 'rizki.elvira@example.com', 'hashedpassword18', 28, 'Suka jalan-jalan keliling kota, tapi belum pernah naik angkutan umum sendirian.', 'https://example.com/photos/rizki_elvira.jpg', NOW(), NOW()),
        (FALSE, 'Eko Nugroho', 'male', 'eko.nugroho@example.com', 'hashedpassword19', 32, 'Sering bangun pagi dengan niat sehat, tapi akhirnya tidur lagi sampai siang.', 'https://example.com/photos/eko_nugroho.jpg', NOW(), NOW()),
        (TRUE, 'Lia Salsabila', 'female', 'lia.salsabila@example.com', 'hashedpassword20', 30, 'Penyuka cats, tapi selalu kaget kalau kucingnya mulai berlari di tengah malam.', 'https://example.com/photos/lia_salsabila.jpg', NOW(), NOW()),
        (FALSE, 'Rizal Alamsyah', 'male', 'rizal.alamsyah@example.com', 'hashedpassword21', 28, 'Hobi nonton konser, tapi lebih sering mendengarkan musik di rumah sendiri.', 'https://example.com/photos/rizal_alamsyah.jpg', NOW(), NOW()),
        (TRUE, 'Adelia Putri', 'female', 'adelia.putri@example.com', 'hashedpassword22', 27, 'Bergaya minimalist, tapi suka beli barang-barang yang nggak terlalu dibutuhkan.', 'https://example.com/photos/adelia_putri.jpg', NOW(), NOW()),
        (FALSE, 'Joko Ristanto', 'male', 'joko.ristanto@example.com', 'hashedpassword23', 34, 'Sering menjadi driver online, tapi malah suka bengong sambil nunggu penumpang.', 'https://example.com/photos/joko_ristanto.jpg', NOW(), NOW()),
        (TRUE, 'Alya Pratiwi', 'female', 'alya.pratiwi@example.com', 'hashedpassword24', 29, 'Suka ikut challenge di Instagram, tapi selalu lupa saat harus live streaming.', 'https://example.com/photos/alya_pratiwi.jpg', NOW(), NOW()),
        (FALSE, 'Gilang Maulana', 'male', 'gilang.maulana@example.com', 'hashedpassword25', 30, 'Penyuka olahraga, tapi sering kalah sama teman-teman dalam permainan bola voli.', 'https://example.com/photos/gilang_maulana.jpg', NOW(), NOW()),
        (TRUE, 'Fariha Aziza', 'female', 'fariha.aziza@example.com', 'hashedpassword26', 26, 'Suka memasak, tapi lebih sering pesen makanan lewat aplikasi.', 'https://example.com/photos/fariha_aziza.jpg', NOW(), NOW()),
        (FALSE, 'Dimas Hariyanto', 'male', 'dimas.hariyanto@example.com', 'hashedpassword27', 28, 'Hobi menulis, tapi lebih banyak nulis caption Instagram daripada buku.', 'https://example.com/photos/dimas_hariyanto.jpg', NOW(), NOW()),
        (TRUE, 'Cynthia Maharani', 'female', 'cynthia.maharani@example.com', 'hashedpassword28', 32, 'Sering bilang akan mulai diet, tapi akhirnya pesan es krim dalam jumlah banyak.', 'https://example.com/photos/cynthia_maharani.jpg', NOW(), NOW()),
        (FALSE, 'Budi Santoso', 'male', 'budi.santoso@example.com', 'hashedpassword29', 33, 'Sering nonton video YouTube tentang teknologi, tapi belum pernah mengerti apa itu IoT.', 'https://example.com/photos/budi_santoso.jpg', NOW(), NOW()),
        (TRUE, 'Nina Ratnasari', 'female', 'nina.ratnasari@example.com', 'hashedpassword30', 27, 'Bergaya casual, tapi sering merasa seperti fashionista yang tak terduga.', 'https://example.com/photos/nina_ratnasari.jpg', NOW(), NOW()),
        (FALSE, 'Hendra Saputra', 'male', 'hendra.saputra@example.com', 'hashedpassword31', 32, 'Penggila mobil, tapi sering kebingungan pas disuruh ganti oli sendiri.', 'https://example.com/photos/hendra_saputra.jpg', NOW(), NOW());




COMMIT;